Code Clean-up and Restructuring (#82)
* Chore: remove unnecessary backups and pycaches

* Style: format the codebase with `black` and `isort`

* Refactor: remove unused imports

* Refactor(main): remove unused and commented out code

* Fix: remove deprecated `awoc` library

* Fix: update `openai` to resolve `TypeError`

self._client = http_client or httpx.Client( TypeError: __init__() got an unexpected keyword argument 'proxies'

* Build(Dockerfile): remove redundant installs

* Chore: untrack `data` and `models` directories

* Build: add dependencies for Azure Storage IO

* Refactor: decouple data from the application code

All KG and model data are now read from the Azure Blob container

* Chore: remove redundant `notebooks` directory

* Chore: remove redundant `testing` directory

* Refactor(utils): remove unused modules and functions

* Refactor(src): remove unused `json_image` module

* Refactor(src): move utils modules to `src`

* Build: remove unused dependencies

* Build(Dockerfile): remove redundant installs

* Refactor(src): rename modules for clarity and brevity

* Refactor: use `snake_case` for function names

* Refactor(main): remove `ThreadPoolExecutor` for simplicity

* Refactor: add generic `genai` functions to simplify the codebase

Also remove unused function arguments.

* Refactor(main): remove redundant variables and calls

* Refactor(src): generalise `generate_response` function with `kwargs`

* Build: update `numpy` and `faiss` to the latest versions

* Build: update core project dependencies

* Build: add development dependencies

* Chore: add a `Makefile` for executing routines

* Build(Dockerfile): use a newer Python version and no cache

* Refactor(genai): use a shorter env variable name for API key

* CI: update the deployment script

* Docs: add BSD 3 license

* Docs: update the readme file

* Chore: add a pull request template